
package examennicolas;

/**
 *
 *
 */
public class EJ03 extends javax.swing.JFrame {

    int MES, FECHA, DIA;
    String nm;
    
    public EJ03() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Labelmes = new javax.swing.JLabel();
        labelaño = new javax.swing.JLabel();
        Txtaño = new javax.swing.JTextField();
        Txtmes = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        solucion = new javax.swing.JTextArea();
        procesar = new javax.swing.JButton();
        borrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Labelmes.setFont(new java.awt.Font("Oswald", 1, 14)); // NOI18N
        Labelmes.setText("Mes");

        labelaño.setFont(new java.awt.Font("Oswald", 1, 14)); // NOI18N
        labelaño.setText("Año");

        solucion.setColumns(20);
        solucion.setRows(5);
        jScrollPane1.setViewportView(solucion);

        procesar.setText("Procesar");
        procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesarActionPerformed(evt);
            }
        });

        borrar.setText("Borrar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelaño, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txtaño, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 20, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Labelmes, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txtmes, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(procesar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Labelmes)
                    .addComponent(Txtmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(procesar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelaño)
                    .addComponent(Txtaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
       eliminar();
    }//GEN-LAST:event_borrarActionPerformed

    private void procesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesarActionPerformed
        MES = Integer.parseInt(Txtmes.getText());
        FECHA = Integer.parseInt(Txtaño.getText());
        
        switch (MES){
            case 1 -> {
                nm = "Enero";
                DIA = 31;
                solucion.setText("MES: "+nm+"\nDIA: "+DIA);
            }
                
            case 2 -> {
                if (FECHA%4==0){
                    nm = "Febrero";
                    DIA = 29;
                }else{
                    nm = "Febrero";
                    DIA = 28;
                }
                solucion.setText("MES: "+nm+"\nDIA: "+DIA);
            }
                
            case 3 -> {
                nm = "Marzo";
                DIA = 31; 
                solucion.setText("MES: "+nm+"\nDIA: "+DIA);
            }
                
            case 4 -> {
                nm = "Abril";
                DIA = 30;
                solucion.setText("MES: "+nm+"\nDIA: "+DIA);
            }
                
            case 5 -> {
                nm = "Mayo";
                DIA = 31;
                solucion.setText("MES: "+nm+"\nDIA: "+DIA);
            }
                
            case 6 -> {
                nm = "Junio";
                DIA = 30; 
                solucion.setText("MES: "+nm+"\nDIA: "+DIA);
            }
                
            case 7 -> {
                nm = "julio";
                DIA = 31; 
                solucion.setText("MES: "+nm+"\nDIA: "+DIA);
            }
                
            case 8 -> {
                nm = "Agosto";
                DIA = 31;
                solucion.setText("MES: "+nm+"\nDIA: "+DIA);
            }
                
            case 9 -> {
                nm = "Septiembre";
                DIA = 30;
                solucion.setText("MES: "+nm+"\nDIA: "+DIA);
            }
                
            case 10 -> {
                nm = "Octubre";
                DIA = 31;
                solucion.setText("MES: "+nm+"\nDIA: "+DIA);
            }
                
            case 11 -> {
                nm = "Noviembre";
                DIA = 30;
                solucion.setText("MES: "+nm+"\nDIA: "+DIA);
            }
                
            case 12 -> {
                nm = "Diciembre";
                DIA = 31;
                solucion.setText("MES: "+nm+"\nDIA: "+DIA);
            }
                
            default -> { 
                nm = "ERROR";
                DIA = 00;
            }
        }           
    }//GEN-LAST:event_procesarActionPerformed

    void eliminar(){
        Txtmes.setText("");
        Txtaño.setText("");
        solucion.setText("");
        Txtmes.requestFocus();
    }  

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EJ03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EJ03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EJ03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EJ03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EJ03().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Labelmes;
    private javax.swing.JTextField Txtaño;
    private javax.swing.JTextField Txtmes;
    private javax.swing.JButton borrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelaño;
    private javax.swing.JButton procesar;
    private javax.swing.JTextArea solucion;
    // End of variables declaration//GEN-END:variables
}
